### ISSUE TITLE
Samuel needs to shave 

### ISSUE THREAD

**Issue by joegentine** [samuelDLP/Catan-Simulation#4]

**Comment by samuelDLP** [comment]
I'll work on it 👍

**Comment by samuelDLP** [comment]
![WIN_20201218_14_47_04_Pro](https://user-images.githubusercontent.com/69833615/102655235-f55a1a00-413f-11eb-8af1-28a8864a40fe.jpg)

**Comment by samuelDLP** [comment]
@joegentine closed issue with proof
